[package]
name = "imbl-value"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imbl = { version = "2.*", features = ["serde"] }
serde_json = "1.*"
serde = { version = "1.*", features = ["derive", "rc"] }
treediff = { version = "4.*", optional = true }
